stages:
  - building
  - deploying

variables:
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
build-prod-stage:
  stage: building
  tags:
   - builder
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  image: tiangolo/docker-with-compose
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build . -t $REGISTRY_URL:$CONTAINER_TAG
    - docker push  $REGISTRY_URL:$CONTAINER_TAG
deploy-prod-stage:
  stage: deploying
  tags:
   - deployer
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  script:
    - sed -i "s/calculator:*/calculator:$CONTAINER_TAG/g" deployment.yml
    - kubectl apply -f deployment.yml
    - kubectl apply -f service.yml
    - kubectl apply -f ingress.yml 

