stages:
  - building
  - deploying

variables:
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}

  #before_script:
  #  - docker login -u amirhseta -p 13771377a
build-prod-stage:
  stage: building
  tags:
   - building
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  image: tiangolo/docker-with-compose
  script:
    - sed -i "s/nameserver 8.8.8.8/nameserver 178.22.122.100/g" /etc/resolv.conf ;  docker login -u amirhseta -p 13771377a
    - docker build . -t amirhseta/calculator:$CONTAINER_TAG
    - docker push  amirhseta/calculator:$CONTAINER_TAG
deploy-prod-stage:
  stage: deploying
  tags:
   - deploying
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  script:
    - sed -i "s/latest/$CONTAINER_TAG/g" deployment.yml
    - kubectl apply -f deployment.yml
    - kubectl apply -f service.yml
    - kubectl apply -f ingress.yml 

