stages:
  - building
  - deploying

variables:
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}

build-prod-stage:
  stage: building
  tags:
   - builder
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  image: tiangolo/docker-with-compose
  script:
    - docker login -u amirhseta -p 13771377a
    - docker build . -t amirhseta/calculator:$CONTAINER_TAG
    - docker push  amirhseta/calculator:$CONTAINER_TAG
deploy-prod-stage:
  stage: deploying
  tags:
   - kubernetes
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  script:
    - ssh amirtaghia@127.0.0.1
    - echo aA12345 | sudo -S sed -i "s/latest/$CONTAINER_TAG/g" deployment.yml
    - echo aA12345 | sudo -S runuser -l amirtaghia -c "kubectl apply -f deployment.yml"
    - echo aA12345 | sudo -S runuser -l amirtaghia -c "kubectl apply -f service.yml"
    - echo aA12345 | sudo -S runuser -l amirtaghia -c "kubectl apply -f ingress.yml" 

