stages:
  - build
  - test
  - deploy

cache:
  key:
    files:
      - package-lock.json
  paths:
    - node_modules/

variables:
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}

before_script:
  - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD


build-stage:
  stage: build
  tags:
   - builder
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  image: tiangolo/docker-with-compose
  script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASSWORD
    - docker build . -t $REGISTRY_URL:$CONTAINER_TAG
    - docker push  $REGISTRY_URL:$CONTAINER_TAG

test-stage:
  stage: test
  needs:
    - build-stage
  script: npm run test


deploy-stage:
  stage: deploy
  tags:
   - deployer
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  script:
    - sed -i "s/:latest/:$CONTAINER_TAG/g" deployment.yml
    - kubectl apply -f deployment.yml
    - kubectl apply -f service.yml
    - kubectl apply -f ingress.yml 

