stages:
  - building
  - deploying

variables:
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}

build-prod-stage:
  stage: building
  tags:
   - docker
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  image: tiangolo/docker-with-compose
  script:
    - docker build . -t amirhseta/calculator:$CONTAINER_TAG
    - docker push  amirhseta/calculator:$CONTAINER_TAG
deploy-prod-stage:
  stage: deploying
  tags:
   - kuber
  variables:
    FF_GITLAB_REGISTRY_HELPER_IMAGE: "false"
  image: tiangolo/docker-with-compose
  script:
    - kubectl delete -f deployment
    - sed -i 's/"image: 192.168.89.13:5000/calculator:latest"/"image: 192.168.89.13:5000/calculator:$CONTAINER_TAG"/g' deployment.yml
    - kubectl apply -f deployment.yml

