apiVersion: v1
kind: Service
metadata:
  name: calculator-service
spec:
  selector:
    app: calculator
  ports:
    - name: http
      protocol: TCP
      port: 80      
      targetPort: 3000            
